# Generated by Django 3.0.5 on 2020-04-10 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('page', models.IntegerField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
    ]
