# Generated by Django 3.0.5 on 2020-04-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_demo_register_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
